### ISSUE TITLE
ElementNotFoundException: GUA.config form does not exists

### ISSUE THREAD

**Issue by neywen** [thelia-modules/GoogleUniversalAnalytics#1]
I have a thelia 2.0.2 installed and working,
I've cloned the googleUniversalAnalytics repository, made a checkout on the branch 2.0,
installed the module at the proper place, activated the module, and clicked the "configure" button.

An exception is raised : ElementNotFoundException: GUA.config form does not exists

I'll try and figure out something, but if anyone has an idea....

thanks.

**Comment by neywen** [comment]
I've switched to another version of the module, found on github. It did not have the same bug, but does not work as expected once executed. Switched back to the previous module, and then, did not have the bug anymore. Problem solved, but I don't know how exactly, though... :)

**Comment by lunika** [comment]
the cache was probably not reset.

**Comment by neywen** [comment]
Ok, thank you for your message, I'll keep that in mind. Indeed, I did not think about cleaning the cache, that should have been my first thought.
